### ISSUE TITLE
Erstellung Planung für wls-service-infomanagement

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#102]
- [x] Issues sind erstellt
- [x] Abhängigkeiten sind gepflegt
- [x] Zuordnung zu Epic und Milestone ist gepflegt

---

# Hinweise
- Planung für Broadcast-Service kann als Grundlage zu notwendigen Schritte verwendet werden
  - Issue: #16
  - Epic: #5
  - zusätzliche Schritte die initial bei #16 nicht explicit erwähnt wurden
    - Erstellung Swagger-Beschreibung
	- Verwendung von Flyway
	  - Beispiel:
	    - [sql-File]( https://github.com/it-at-m/Wahllokalsystem/blob/2a2d0485d8028efea4d6731d360dd472220f1348/wls-broadcast-service/src/main/resources/db/migrations/oracle/V0_1__createTableTheEntity.sql)
		- [PR mit Flyway](#79)
- Pflege Keycloak bis Auth-Service steht
- Verwendung von `DummyBezirkIdPermissionEvaluatorImpl` bis Auth-Service steht

# Ergebnis aus schnellem Check
- 2 Repos je mit Service
- 1 Controller vor den Services

**Comment by dragonfly28** [comment]
# Neue Issues

## 1 - Implementierung von Konfiguration Wahltag
Controller -> Service -> Repo für:
- [ ] Lesen/Aktualisieren/Löschen eines konfigurierten Wahltags, siehe:
  - getKonfigurierterWahltag -> GetKonfigurierterWahltag_BusinessActionServiceImpl -> konfigurierterWahltagRepository
  - postKonfigurierterWahltag -> PostKonfigurierterWahltag_BusinessActionServiceImpl -> konfigurierterWahltagRepository
  - deleteKonfigurierterWahltag -> DeleteKonfigurierterWahltag_BusinessActionServiceImpl -> konfigurierterWahltagRepository
- [ ] Lesen aller konfigurierten Wahltage, siehe:
  - getKonfigurierteWahltage -> GetKonfigurierteWahltage_BusinessActionServiceImpl -> konfigurierterWahltagRepository
- [ ] Lesen Login-Flag, siehe:
  - getLoginCheck -> GetLoginCheck_BusinessActionServiceImpl -> konfigurierterWahltagRepository
- [ ] Zugriffsrechte sind gepflegt
- [ ] DB-Schema mittels Flyway aktualisiert 
- [ ] Erstellung Swagger-Beschreibung


## 2 - Implementierung Wahlkonfiguration
Controller -> Service -> Repo für:
- [ ] Lesen/Speichern der Wahlkonfiguration, siehe:
  - getKonfiguration -> GetKonfiguration_BusinessActionServiceImpl -> konfigurationRepository
  - setKonfiguration -> PostKonfiguration_BusinessActionServiceImpl -> konfigurationRepository
- [ ] Lesen der Wahlkonfiguration ohne Authorisierung, siehe:
  - getKonfigurationUnauthorized -> GetKonfigurationUnauthorized_BusinessActionServiceImpl -> konfigurationRepository
- [ ] Lesen aller Wahlkonfigurationen, siehe:
  - getKonfigurationen -> GetKonfigurationen_BusinessActionServiceImpl -> konfigurationRepository
- [ ] Lesen der Kennbuchstabenlisten
  - getKennbuchstabenListen -> GetKennbuchstabenListen_BusinessActionServiceImpl -> konfigurationRepository
- [ ] Zugriffsrechte sind gepflegt
- [ ] DB-Schema mittels Flyway aktualisiert 
- [ ] Erstellung Swagger-Beschreibung

**Comment by MrSebastian** [comment]
entsprechend Review von heute den Punkt `und im Produkt Backlog` entfernt
