### ISSUE TITLE
Erstellung Planung für wls-service-vorfaelleundvorkommnisse

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#123]
- [x] Issues sind erstellt
- [x] Abhängigkeiten sind gepflegt
- [x] Zuordnung zu Epic und Milestone ist gepflegt

---

# Hinweise
- Planung für Broadcast-Service kann als Grundlage zu notwendigen Schritte verwendet werden
  - Issue: #16
  - Epic: #5
  - zusätzliche Schritte die initial bei #16 nicht explicit erwähnt wurden
    - Erstellung Swagger-Beschreibung
	- Verwendung von Flyway
	  - Beispiel:
	    - [sql-File]( https://github.com/it-at-m/Wahllokalsystem/blob/2a2d0485d8028efea4d6731d360dd472220f1348/wls-broadcast-service/src/main/resources/db/migrations/oracle/V0_1__createTableTheEntity.sql)
		- [PR mit Flyway](#79)
- Pflege Keycloak bis Auth-Service steht
- Verwendung von `DummyBezirkIdPermissionEvaluatorImpl` bis Auth-Service steht

# Ergebnis aus schnellem Check
- 1 mal Controller->Service->Repo

**Comment by dragonfly28** [comment]
# Neue Issues

## 1 - Implementierung von Speichern und Auslesen von Ereignissen für Wahlbezirke
- [ ] Ereignisse (Vorfälle/Vorkomnisse) können für einen Wahlbezirk gespeichert und gelesen werden
- [ ] Zugriffsrechte sind gepflegt
- [ ] DB-Schema mittels Flyway aktualisiert 
- [ ] Erstellung Swagger-Beschreibung
- Controller -> Service -> Repo

**Comment by MrSebastian** [comment]
entsprechend Review von heute den Punkt `und im Produkt Backlog` entfernt
