### ISSUE TITLE
Implementierung von Speichern und Auslesen von Ereignissen für Wahlbezirke

### ISSUE THREAD

**Issue by dragonfly28** [it-at-m/Wahllokalsystem#137]
### Implementierung des Service wls-service-vorfaelleundvorkommnisse
Nochmal zur Erinnerung:
- Controller -> Service -> Repo
- DTOs mit Records
- Service hat eigenes Datenmodell: *Modell-Klassen (auch Records)
- Controller und Service verwenden DTOs als Datenklassen (die selben)
- Service gibt **keine** Entitäten raus: nur DTOs
- Kommunikation: Controller -> Service -> Repo
- Datenzugriff via Entitäten
- Mapping mit MapStruct
- inklusive Security

#### Speichern und Auslesen von Ereignissen für Wahlbezirke
- [x] Eine Liste an Ereignissen (Typ Vorfälle/Vorkomnisse) kann für einen Wahlbezirk gespeichert und ausgelesen werden
- [x] Zugriffsrechte sind gepflegt
- [x] DB-Schema mittels Flyway aktualisiert 
- [x] Erstellung Swagger-Beschreibung

**Comment by vjohnslhm** [comment]
Ein Test ist nicht korrekt benannt und ein anderer wurde falsch genested, daher reopen
