### ISSUE TITLE
Wahlen können gelesen und geschrieben werden

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#141]
# Akzeptanzkriterien

- [x] Wahlen können gelesen und geschrieben werden
- [x] sind beim Lesen keine Daten vorhanden werde diese importiert
- [x] Zugriffsrechte sind gepflegt
- [x] Erstellung Swagger-Beschreibung
- [x] DB-Schema mittels Flyway aktualisiert 

# Umsetzungshinweise

- Controller -> Service -> Repo

**Comment by MrSebastian** [comment]
#144 für die Erfahrung mit der EAI-Anbindung

**Comment by Nic12345678** [comment]
Schreiben von Wahlen hat bei Demo nicht funktioniert, die alten Wahlen wurden nicht überschrieben.
