### ISSUE TITLE
Implementierung der Pflege von Wahltermindaten

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#148]
# Akzeptanzkriterien

- [x] Wahltermindaten können erstellt werden (mittels Import)
- [x] Wahltermindaten können gelöscht werden (vollständige Transaktion)

# Umsetzungshinweise
- da das Importieren länger dauern kann soll dies asynchron erfolgen
- ist im Prinzip eine Initialisierung oder Löschung aller Daten

**Comment by Nic12345678** [comment]
@MrSebastian Ich glaube wir sollen bei Wahlvorschlaege-Wahlvorschlag und Referendumvorlagen-Referendumvorlage die Beziehungen auf ManyToMany ändern. Die Wahlvorschlaege einer wahlbezirkID sind Parteien  (Wahlvorschlag) und sind die gleichen in mehreren Wahlbezirken. OneToMany und ManyToOne führt dazu, dass alle Parteien eines Wahlbezirks aus der DB unterschiedliche id-s haben müssen als die gleichen Parteien eines anderen Wahlbezirks. Das produziert zum einen viele Daten und zum anderen bin ich ir nicht sicher ob sie sogar von IVU so geliefert werden.

Ich lade die Wahlvorschlaege von 2 unterschiedlichen Wahlbezirken - sie habe gleiche identifikator.
[wb2.json](https://github.com/user-attachments/files/16730144/wb2.json)
[wb1.json](https://github.com/user-attachments/files/16730145/wb1.json)

**Comment by Nic12345678** [comment]
Ein anderer Gedankenanstoß über die Modellierung, speziell der Wahlvorschlaege und Referendumvorschlaege. Wenn die Sub-Entities der gleichen Ebene, den gleichen Identifikator haben, dann kommt "Suppressed: org.springframework.dao.DataIntegrityViolationException"

**Comment by MrSebastian** [comment]
Es fehlt ein Test in `SecurityConfigurationTest`
