### ISSUE TITLE
Implementierung Broadcast-Service

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#16]
- DTOs mit Records
- Service hat eigenes Datenmodell: *Modell-Klassen (auch Records)
- Controller und Service verwenden DTOs als Datenklassen (die selben)
- Service gibt **keine** Entitäten raus: nur DTOs
- Kommunikation: Controller -> Service -> Repo
- Datenzugriff via Entitäten
- Mapping mit MapStruct
- inklusive Security

**Comment by Nic12345678** [comment]
@MrSebastian @dragonfly28 @GerhardPx 
Sollen wir Swagger gleich einbauen? Er müsste von der Security ausgeschlossen werden. Oder machen wir später in einem anderen Sprint?

**Comment by MrSebastian** [comment]
kann gerne mit rein

**Comment by MrSebastian** [comment]
rein formal könnte man sagen es ist nicht Teil der Anforderungen und somit ein Change und deshalb ein neues Issue
