### ISSUE TITLE
Implementierung Monitoring Wahlbeteiligung

### ISSUE THREAD

**Issue by dragonfly28** [it-at-m/Wahllokalsystem#169]
### Implementierung des Service wls-service-monitoring

wls-service-monitoring besteht aus 1 Controller -> 1 Service -> 1 Repo + EAI

Related to #170: beiden gehen auf aoueai (Generierung abstimmen)

#### Lesen der Wahlbeteiligung (getWahlbeteiligung)
- [x] Die Wähleranzahl wird für eine wahlID und wahlbezirkID gelesen
- [x] Zugriffsrechte sind gepflegt
- [x] DB-Schema mittels Flyway aktualisiert 
- [x] Erstellung Swagger-Beschreibung

#### Speichern und Weiterleiten der Wahlbeteiligung (postWahlbeteiligung)
- [x] Die Wähleranzahl wird gespeichert
- [x] Die Wahlbeteiligung wird an die EAI übermittelt
- [x] Zugriffsrechte sind gepflegt
- [x] DB-Schema mittels Flyway aktualisiert 
- [x] Erstellung Swagger-Beschreibung

**Comment by Nic12345678** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/169?planning-poker) with Zenhub @dragonfly28 @GerhardPx @MrSebastian @vjohnslhm
