### ISSUE TITLE
Implementierung Monitoring Zeitstempel-Aktionen

### ISSUE THREAD

**Issue by dragonfly28** [it-at-m/Wahllokalsystem#170]
### Implementierung der Zeitstempel-Aktionen welche ausschliesslich an die EAI übermittelt werden

wls-service-monitoring besteht aus 1 Controller -> 1 Service -> 1 Repo + EAI

Related to #169: beiden gehen auf aoueai (Generierung abstimmen)

#### Speichern der Uhrzeit zu der das Wahllokal zuletzt gesehen wurde (postLastSeen)
- [x] Uhrzeit wird über EAI gespeichert
- [x] Zugriffsrechte sind gepflegt
- [x] Erstellung Swagger-Beschreibung

#### Speichern der Uhrzeit zu der das Wahllokal zuletzt abgemeldet wurde (postLetzteAbmeldung)
- [x] Uhrzeit wird über EAI gespeichert
- [x] Zugriffsrechte sind gepflegt
- [x] Erstellung Swagger-Beschreibung

#### Speichern der Uhrzeit zu der die Niederschrift gedruckt wurde (postNiederschriftDruckuhrzeit)
- [x] Uhrzeit wird über EAI gespeichert
- [x] Zugriffsrechte sind gepflegt
- [x] Erstellung Swagger-Beschreibung
 
#### Speichern der Uhrzeit zu der die Niederschrift gesendet wurde (postNiederschriftSendungsuhrzeit)
- [x] Uhrzeit wird über EAI gespeichert
- [x] Zugriffsrechte sind gepflegt
- [x] Erstellung Swagger-Beschreibung
 
#### Speichern der Uhrzeit zu der die Schnellmeldung gedruckt wurde (postSchnellmeldungDruckuhrzeit)
- [x] Uhrzeit wird über EAI gespeichert
- [x] Zugriffsrechte sind gepflegt
- [x] Erstellung Swagger-Beschreibung
 
#### Speichern der Uhrzeit zu der die Schnellmeldung gesendet wurde (postSchnellmeldungsSendungsuhrzeit)
- [x] Uhrzeit wird über EAI gespeichert
- [x] Zugriffsrechte sind gepflegt
- [x] Erstellung Swagger-Beschreibung

**Comment by Nic12345678** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/170?planning-poker) with Zenhub @dragonfly28 @GerhardPx @MrSebastian @vjohnslhm

**Comment by MrSebastian** [comment]
auf Branch zu Issue #169 aufsetzen da 169 vorher kommen wird

**Comment by MrSebastian** [comment]
Flyway-Todos aus Beschreibung entfernt da in diesem Issue keine Persistierung umzusetzen war
