### ISSUE TITLE
Verbesserung EncryptionBuilder - inversion of control für ciphers

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#172]
Der Encryption-Builder (wls-common:security) erzeugt aktuell seine Ciphers selber.

Es wäre besser wenn der EncryptionBuilder sich auf die Aufgabe des Ver- und Entschlüsselns konzentriert. Daher sollten der Builder die Ciphers von außen erhalten. Einen Fallback halte ich nicht für notwendig.

Hinweis zum Testing:
Im Rahmen der Anpassung kann auch die Branch-Abdeckung der Tests komplettiert werden.

# Akzeptanzkriterien
- [x] EncryptionBuilder ist angepasst

**Comment by Nic12345678** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/172?planning-poker) with Zenhub @dragonfly28 @GerhardPx @MrSebastian @vjohnslhm

**Comment by MrSebastian** [comment]
Akzeptanzkriterien `es sind keine zusätzliche Codeanpassungen in Microservices notwendig` entfernt nach Rücksprache. Macht den Sachverhalt unnötig kompliziert (im Prinzip unmöglich). Aktuel gibt es nur einen Nutzer.
