### ISSUE TITLE
Bereitstellung Datenstrukturen

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#174]
# Akzeptanzkriterien
- [x] Entities: Authorities, Permissions, User, LoginAttempts
- [x] Entity, Repo, Flyway-Skripte

# Umsetzungshinweise
- Übernahme von generierten Klassen ohne Implementierungslogik sollte vermieden werden (z.b. bei `*EventListener`)
- Decorator und Processor Klasse im Repositories-Package beachten!!!

**Comment by Nic12345678** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/174?planning-poker) with Zenhub @dragonfly28 @GerhardPx @MrSebastian @vjohnslhm

**Comment by MrSebastian** [comment]
Die Grafik in der Doku spiegelt nicht den aktuellen Stand wieder. Zwischen `User` und `Authority` sowie zwischen `Authority` und `Permission` liegt eine m-n-Beziehung vor. Die Grafik zeigt eine `1-n-Beziehung

**Comment by MrSebastian** [comment]
> Die Grafik in der Doku spiegelt nicht den aktuellen Stand wieder. Zwischen `User` und `Authority` sowie zwischen `Authority` und `Permission` liegt eine m-n-Beziehung vor. Die Grafik zeigt eine `1-n-Beziehung

soll durch #513 gefixt werden
