### ISSUE TITLE
Lesen und schreiben von Fehlercodes

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#188]
# Akzeptanzkriterien
- [ ] Lesen von allen vorhanden Fehlercodes möglich
- [ ] Lesen von Fehlercodes für eine Wahlart ist möglich
- [ ] Lesen von einem Fehlercode anhand dessen ID ist möglich
- [ ] Es kann eine Liste von Fehlercode gespeichert werden
  - werden zu den bestehenden ergänzt

# Umsetzungshinweise
- Controller -> Service -> Repo
- Flyway verwendet
- Security ist gepflegt

**Comment by MrSebastian** [comment]
prüfen ob wirklich noch benötigt: @Nic12345678

**Comment by Nic12345678** [comment]
Diese Funktionalität wird nicht mehr benötigt. Es stammt aus der Zeit, als die Validierung gegen das Backend und weiter das WAS stattfand. Sie wurde vom Admin-Tool Frontend benutzt um Fehlermeldungen, anhand von in WAS befindlichen Codes, im Backend von WLS einzustellen und wurde am 27.02.2019 im Admintool mit "Offline-Validierung macht dies Obsolet." auskommentiert, commit message  (für die Suche) `"fehlermeldungen" auskommentiert`. Auf die Funktionalität wurde somit mit der Offline-Fähigkeit verzichtet, der alte Code wurde aus dem ergebnismeldung-service nicht enfernt. Lediglich im FE vom AdminTool wurde der HTM-Code auskommentiert, damit dieser nicht mehr zur Anwendung kommt.  

@MrSebastian 
Ich schlage vor, dieses Issue zu schließen.

**Comment by MrSebastian** [comment]
ja - gerne das Issue schließen. Kannst gerne das Label `wont fix` setzen. Trenne es am besten aus dem Milestone, Release und Epic raus da hier nichts zu tun war.

**Comment by Nic12345678** [comment]
Es war zu recherchieren! Ich habe etwas Zeit investiert :)
