### ISSUE TITLE
wls-briefwahl-service - enable und implement Tests

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#201]
Im Rahmen von #119 wurden Tests deaktiviert weil diese mit spring-data-rest-arbeiten was wir aber bei uns in den Services nicht verwenden. Sobald Controller vorhanden sind können die Tests wieder aktiviert werden und entsprechend auf die Controller umgeschrieben werden.

- [ ] TheEntity, BaseEntity, TheEntityRepository sind entfernt (Flyway beachten, Drop Table TheEntity);

Hinweis: für die Aktivierung der oberen Tests, geeignete Elemente (ein exemplarischer Controller und Repository) verwenden;

**Comment by Nic12345678** [comment]
see also [MR 440 ](https://github.com/it-at-m/Wahllokalsystem/pull/440) and [Issue 209](https://github.com/it-at-m/Wahllokalsystem/issues/209) sowie [PR 446](https://github.com/it-at-m/Wahllokalsystem/pull/446) und [Issue 380](https://github.com/it-at-m/Wahllokalsystem/issues/380)
