### ISSUE TITLE
Erstellung Releasekandidatversion von wls-common

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#22]
- ist notwendig zur Verwendung für die kommenden Services
- technische Inspiration durch [itm-codeformatter](https://github.com/it-at-m/itm-java-codeformat) möglich
- Workflow muss erstellt werden
  - Artefakt muss gepublished werden
  - Version 1.0.0-RC1
    - nach erfolgreicher Verwendung in einem ersten Service kann die Version final werden (#23) kann RC1 wegfallen

**Comment by MrSebastian** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/22?planning-poker) with Zenhub @dragonfly28 @GerhardPx @Nic12345678

**Comment by dragonfly28** [comment]
So wie es aussieht, muss das Monitoring durch die Weiterentwicklung des Spring Frameworks nicht mehr per Hand gemacht werden. Unter actuator/metrics finden sich standardmäßig eine Vielzahl an Metriken (siehe [Spring Boot Metrics).](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/actuator.html#actuator.metrics) Das muss dann mit dem aktuellen Dashboard in Grafana abgeglichen werden.
Vorschlag wäre daher dass wir den ersten Service nach OpenShift bringen und diesen dann mit dem Grafana Dashboard zusammen bringen:
- URL abgleichen unter der Daten abgegriffen werden
- Daten im Dashboard identifizieren, welche nicht angeboten werden und ggf. händisch nachimplmentiert werden müssen
- Verwendung JMX Bean mit Jolokia abfragen
