### ISSUE TITLE
Erstellen der Epics und der Umsetzungsreihenfolge

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#3]
- [x] die Epics für die Services sind definiert
- [x] die Reihenfolge der Umsetzung der Services ist erkennbar
  - durch Reihenfolge der Epics in Zenhub
- [x] soweit möglich sind Issues basierend auf der Erfahrung der ersten Serviceumstellung erstellt

**Comment by MrSebastian** [comment]
# benötigte Services

## Backend
- Wahlvobereitung
- Vorfälle und Vorkommnisse
- Admin
- Briefwahl
- Monitoring
- Ergebnismeldung
- Infomanagement
- Basisdaten
- Wahlvorstand

## Gateway + UI
- [ ] WLS-Gui
- [ ] Admin-GUI

## EAI
- [ ] API + Mock-Impl

## Infra-Services
- [ ] auth-Service

# Vorschlag Reihenfolge Backend + EAI:
1. API + Mock-Impl
1. auth-Services
1. Vorfälle und Vorkommnisse
1. Basisdaten
1. Infomanagement
1. Monitoring
1. Briefwahl
1. Wahlvobereitung
1. Admin
1. Wahlvorstand
1. Ergebnismeldung

**Comment by MrSebastian** [comment]
Vorschlag für Aufteilung der Epics in Issues je Backend-Service:
- generierung mit Archetype und aufsetzen der Workflows erstellung Abschnitt in Doku; erstellung Benutzer in DB
- je Kette: Controller->Service->Repo ein Issue
  - umfasst auch Update der Keycloak-Config (bis Auth-Service steht)
  - ist alles ein Controller aber mehrere Services mit unterschiedlichen Repos dann darauf aufteilen
  - Wahlvorbereitung: 7 Repos jedes kann eigene Kette bekommen
  - Vorfälle und Vorkommnisse: 1 Repo -> 1 Kette
  - Briefwahl: 2 Repos -> 2 Ketten
  - Monitoring: 1 Repo + 5 Aktionen die EAI vernwenden + 1 Hybrid Repo+EAI -> 7 Ketten
  - Ergebnismeldung: 8 Repos jeweilis mit eigenen Services + 1 Service der zahlreiche Repos verwendet; einzelne Services haben Repo + EAI -> 9 Ketten + EAI-Vorbeit für Hybride
  - Admin: Verwendung von 4 anderen Services -> kann in einem Issue erfolgen; mögliche Subresourcen: wahltage, wahlen, wahltermindaten, benutzer -> 4 Ketten
  - Infomanagement: 1 Controller; 2 Services zu 2 Repos -> 2 Issues für Umsetzung +1 für Controller davor setzen
  - Basisdaten: 8 Ketten; 1 Service der vor den anderen Services sitzt (deleteAll); es gibt Services die auf anderen Repos/Services oder EAI
  - Wahlvorstand: 1 Kette
  - EAI: 12 Resourcen die auf 4 Services zugreifen ->4 Issues

**Comment by MrSebastian** [comment]
Templates für Issues in Doku hinterlegen oder Issue-Templates?

**Comment by Nic12345678** [comment]
> Templates für Issues in Doku hinterlegen oder Issue-Templates?

Ich bin für Issue-Teplate, aber auch Beides wäre hilfreich. Auch wenn die beiden Stellen mit der Zeit inhaltlich auseinander gehen.
