### ISSUE TITLE
Demo-Elemente aus Basisdatenservice entfernen

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#322]
- [x] Die Demo-Elemente die mit #321 eingeführt wurden sollen aus den Basisdaten-Service entfernt werden.
- [x] DemoDTO, DemoClient, ClientDemoRestController, Demo-Migrationsskripte sowie andere DemoElemente entfernen;
- [x] Service erfolgreich getestet.

**Comment by Nic12345678** [comment]
In der [Beschreibung der Generierung der API-Clients](https://it-at-m.github.io/Wahllokalsystem/guides/how-to-create-client-from-open-api-json.html#eai-client-definieren-und-verwenden) habe ich das Demo-Beispiel gelassen, denn das setzt nicht voraus, dass es im Code auch vorhanden sein muss, es ist ein Beispiel für den Leser.
