### ISSUE TITLE
WahlbriefAuthorities der falsche Gruppe zugeordnet

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#361]
In `add_authorities-briefwahl-wahlbriefdaten.yml` wurden Rechte die zum Briefwahl-Service gehören der Gruppe `allWahlvorbereitungAuthorities` zugewiesen. Die Gruppe ist aber für den `Wahlvorbereitungs-Service`.

# Todo
- ~~[ ] Via Migrationfile:~~
  - Entfernung aus alter Gruppe
  - Zuordnung zu `allBriefwahlAuthorities`
 -  [x] Direkte Korrektur in  `add_authorities-briefwahl-wahlbriefdaten.yml` 
  - Neuaufsetzen Keycloak erforderlich
  - Ticket #248 wird in diesem Zusammenhang wieder neu eröffnet

**Comment by dragonfly28** [comment]
Aktuelles (latest) Keycloak-Plugin für die Migration funktioniert nicht mit unserer Keycloak-Version 20.0.5, die Funktion 'revokeRoleFromGroup' hat keinen Effekt.
Die Verwendung einer älteren Version des Plugin hatte ebenfalls keinen Erfolg.

Deshalb wurde der Ansatz über Migrationsfiles die falsche Zuordnung zu entfernen und dann korrekt zu setzen verworfen. Die falsche Zuordnung in `add_authorities-briefwahl-wahlbriefdaten.yml` wurde nun einfach korrigiert, wodurch ein Neuaufsetzen der Rollen und Gruppen von Keycloak erforderlich ist.
