### ISSUE TITLE
wls-vorfaelleundvorkommnisse-service - enable und implement Tests

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#366]
> Hierfür bitte analog zu #201 ein Issue aufmachen damit wir nicht vergessen den und andere aktuell deaktivierte Tests zu aktivieren.
Die deaktivierten Tests setzen auf spring-data-rest welches wir entfernt haben. Und ohne vorhandene Controller gibt es keine Requests.

_Originally posted by @MrSebastian in https://github.com/it-at-m/Wahllokalsystem/pull/364#discussion_r1679581628_

Im Rahmen von https://github.com/it-at-m/Wahllokalsystem/issues/122 wurden Tests deaktiviert weil diese mit spring-data-rest-arbeiten was wir aber bei uns in den Services nicht verwenden. Sobald Controller vorhanden sind können die Tests wieder aktiviert werden und entsprechend auf die Controller umgeschrieben werden.

- [x] TheEntity, BaseEntity, TheEntityRepository sind entfernt (Flyway beachten, Drop Table TheEntity);

Hinweis: für die Aktivierung der oberen Tests, geeignete Elemente (ein exemplarischer Controller und Repository) verwenden;

**Comment by MrSebastian** [comment]
BaseEntity ist noch vorhanden obwohl es nicht referenziert wird

-> reopen
