### ISSUE TITLE
subpackages unter 'domain' beim service-basisdaten verwenden

### ISSUE THREAD

**Issue by dragonfly28** [it-at-m/Wahllokalsystem#383]
- für eine einheitliche Code-Struktur sollen im package `domain` analog zu den packages `rest` und `services` subpackages angelegt werden und die zugehörigen Klassen dorthin verschoben werden
- Klassen, die aus mehreren subpackages referenziert werden sollen ins subpackage `common`
- package-Struktur unter `test` muss ebenfalls angepasst werden

**Comment by Nic12345678** [comment]
@dragonfly28 falls gewünscht bitte im [PR 448](https://github.com/it-at-m/Wahllokalsystem/pull/448) reviewen.
