### ISSUE TITLE
Schreibweise der Datenbanktabellen-Namen vereinheitlichen 

### ISSUE THREAD

**Issue by Nic12345678** [it-at-m/Wahllokalsystem#389]
Wir sollten diskutieren wie wir es künftig einheitlich die Namen der Datenbanktabellen in den Migrationsskripten schreiben wollen. Groß- oder Kleinschreibung?
"create table Wahl" oder "create table wahl"?

# Akzeptanzkriterien:
  - [x] ausprobieren ob Renaming bei bestehendem File geht ohne Konflikte
  - [x] h2 und oracle
  - [x] Groß-Kleinschreibung bei Properties
  - [x] wenn möglich Umsetzungsissue je Service
  - [x] Update Doku
  
Hinweis:
  - Tabellennamen wie Klassennamen
  - Spaltennamen analog zu Propertynamen
  - SQL-Syntax in UPPERCASE

**Comment by vjohnslhm** [comment]
![grafik](https://github.com/user-attachments/assets/7a542af2-908a-40b7-beed-d4ea7d08edfb)
![grafik](https://github.com/user-attachments/assets/65ec8074-2718-4cb3-bddb-79ad6875b31b)
![grafik](https://github.com/user-attachments/assets/b53e8795-d78c-4c23-a4cd-0c982efae05c)


Wir sollten nicht nur die Tabellennamen anschauen, sondern auch die SQL Befehle und Datentypen einheitlich in Groß- oder Kleinbuchstaben schreiben. An den Beispielen oben sieht man, dass es überall anders ist.

**Comment by MrSebastian** [comment]
# Ergebnis
- ausprobieren ob Renaming bei bestehendem File geht ohne Konflikte
  - h2 und oracle
  - Groß-Kleinschreibung bei Properties
- wenn möglich Umsetzungsissue je Service

- Ab jetzt
- Update Doku
  - Tabellennamen wie Klassennamen
  - Spaltennamen analog zu Propertynamen
  - SQL-Syntax in UPPERCASE
