### ISSUE TITLE
Entfernung von unnötigen Leerzeilen zu Beginn einer Methode

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/Wahllokalsystem#403]
RegEx zum Auffinden:

```
public (?!(record)).*\(.*\).*\{


```  
*ja die Leerzeilen im Regex sind wichtig*
 
Mit dem RegEx können die Methoden gefunden werden die die mit einer Leerzeile beginnen.

Wir sollte keine Leerzeile zum Beginn der Methode haben. Leerzeilen gehören zwischen Methoden oder in Methoden zu Trennung von logischen Blöcken, Kommentare nach Statemens, Definition lokaler Variablen von ersten Statement.

# Todo
- Entfernung der Leerzeilen
- Aufnahme von Labels der Services die davon betroffen sind

**Comment by MrSebastian** [comment]
Kann man dies eventuell mit unseren Lintingtools abdecken?

**Comment by dragonfly28** [comment]
Ich habe eine noch generischere regexp gefunden die auch private Methoden abdeckt:
`\(.*\)\s*\{\s*\n\s*\n`

Erfolgreicher Versuch im checkstyle.xml mit:

`<module name="RegexpMultiline">
        <property name="message" value="Blank line at start of method should be removed"/>
        <property name="format" value="\(.*\)\s*\{\s*\n\s*\n"/>
    </module>`

@MrSebastian Macht es Sinn, das in jedem Projekt zum checkstyle.xml hinzuzufügen? Das Zusammenspiel spotless/checkstyle/IntelliJ ist mir noch nicht ganz klar

**Comment by MrSebastian** [comment]
Wir werden es wohl in jedes File im Projekt einbauen müssen da jeder Services ein eigenes Maven-Projekt ist. Bei einem Multi-Modul-Projekt dürfte es an zentraler Stelle ausreichen.

**Comment by MrSebastian** [comment]
Der RegeEx funktioniert leider nicht in folgenden Fällen

# Mehrzeilige Signatur

<details>
<summary>Codebeispiel</summary>

```java
public record UrnenwahlvorbereitungDTO(@NotNull String wahlbezirkID,
                                       @Schema(requiredMode = Schema.RequiredMode.REQUIRED) long anzahlWahlkabinen,
                                       @Schema(requiredMode = Schema.RequiredMode.REQUIRED) long anzahlWahltische,
                                       @Schema(requiredMode = Schema.RequiredMode.REQUIRED) long anzahlNebenraeume,
                                       @NotNull @Size(min = 1) List<WahlurneDTO> urnenAnzahl) {
    public UrnenwahlvorbereitungDTO(final String wahlbezirkID, final long anzahlWahlkabinen, final long anzahlWahltische, final long anzahlNebenraeume,
            final List<WahlurneDTO> urnenAnzahl) {

        this.wahlbezirkID = wahlbezirkID;
        this.anzahlWahlkabinen = anzahlWahlkabinen;
        this.anzahlWahltische = anzahlWahltische;
        this.anzahlNebenraeume = anzahlNebenraeume;
        this.urnenAnzahl = Objects.requireNonNullElseGet(urnenAnzahl, ArrayList::new);
    }
}
```  
*Die Leerzeile vor `this.wahlbezirkID = wahlbezirkID;` wird nicht detektiert.
</details>

# Leerzeile zu Beginn einer Methode die eine Exception wirft

<details>
<summary>Codebeispiel</summary>

```java
public class ServiceIDFormatter {

    private final String serviceName;

    public ServiceIDFormatter(@Value("${service.info.oid}") final String serviceName) {
        this.serviceName = serviceName;
    }

    public String getId() throws RuntimeException {

        return serviceName;
    }
}
```  
*Die Leerzeile zu Beginn der Method `getId` wird nicht gefunden solange es ein `throw ...` gibt

</details>

**Comment by dragonfly28** [comment]
@MrSebastian Das Verhalten bestimmter RegExp-Ausdrücke im Suchfeld von IntelliJ, bei der Verwendung in checkstyle.xml und in einem Web-Tester wie [https://regex101.com/](https://regex101.com/) ist unterschiedlich und nicht nachvollziehbar. Es handelt sich um ein reines Trial&Error-Spiel. 

So funktioniert folgende RegExp z.B. mit dem WebTester für obige Code-Beispiele:
```
(public|private|protected) (?!(record)).*\((.|\n)*\).*\{\n\n
```
Aber leider nicht in der IntelliJ-Suche und über Checkstyle.


Mein Vorschlag wäre:
-  die im Ticket beschriebene RegExp wenigstens noch auf private und protected Methoden zu erweitern 
-  die Anpassungen einmalig händisch zu machen
-  den Check in checkstyle.xml wieder zu entfernen

```
(public|private|protected) (?!(record)).*\(.*\).*\{


```

**Comment by MrSebastian** [comment]
@dragonfly28 ich stimme deinem Vorschlag zu
