### ISSUE TITLE
naming conventions for testing

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#414]
## Beschreibung

Damit der Code übersichtlicher und einheitlicher ist, sollte überlegt werden, [Naming Conventions](https://dzone.com/articles/7-popular-unit-test-naming) zu befolgen.

## Beispiel

Beispiel für Nr. 5 aus der Liste ("Should_ExpectedBehavior_When_StateUnderTest"-Convention) siehe Vorfälle und Vorkommnisse Service:
```
void should_return_WahlbezirkEreignisseDTO_when_given_valid_wahlbezirkid() {}
```
statt
```
void serviceCalled() {}
```

## Argumente

Folgende Vor- und Nachteile die mir einfallen:

| + | - | 
| ------ | ------ | 
| Vereinheitlichung | längere Methodennamen | 
| bessere Lesbarkeit durch klare Struktur | ggf für einige Testfälle schwierig anzuwenden | 
| einfache Identifizierung von Tests | |

**Comment by MrSebastian** [comment]
# Ergebnis
- Umsetzung ab jetzt
- Je Service ein Umsetzung-Issue
- Update Doku
  - mit Beispielen
- Variante:
  - `should_<result>_when_<Input>`
  - Result und Input in CamelCase
  - Verwendung von  `@Nested` für die zu testenden Methoden
  - Auch nested für überladene Methoden

**Comment by vjohnslhm** [comment]
Issues erstellt für die Services Basisdaten (#429), Briefwahl (#430), Broadcast (#431), EAI (#432), Infomanagement (#434), Wahlvorbereitung (#436), und Wahlvorstand (#437).

Die Services Auth, Ergebnismeldung und Monitoring sind noch nciht implementiert, daher sind keine Anpassungstickets notwendig.
 
Der Service VorfaelleundVorkommnisse wurde bereits umgesetzt (#137)
