### ISSUE TITLE
Auslagern von Authority Strings

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#420]
> Dies Auslagerung an sich gefällt mir und wäre zu überlegen auch auf die anderen Services zu übernehmen.

_Originally posted by @MrSebastian in https://github.com/it-at-m/Wahllokalsystem/pull/412#discussion_r1760907764_

## Beispiel
```
String AUTHORITY_WRITE_EREIGNIS = "hasAuthority('VorfaelleUndVorkommnisse_WRITE_Ereignisse')";
@PreAuthorize(AUTHORITY_WRITE_EREIGNIS)
```
statt
```
@PreAuthorize("hasAuthority('VorfaelleUndVorkommnisse_WRITE_Ereignisse')")
```

## Beschreibung

Das Auslagern der AuthorityStrings hätte folgende Vor- und Nachteile die mir einfallen:

| + | - | 
| ------ | ------ | 
| Wiederverwendbarkeit | mehr Codezeilen | 
| bessere Lesbarkeit | | 
| Reduzierung von Errors durch Tippfehler | |

**Comment by MrSebastian** [comment]
# Entscheidung
- bleibt bei Vorgehen: `@PreAuthorize("hasAuthority('VorfaelleUndVorkommnisse_WRITE_Ereignisse')")`
  - keine gesonderten Konstanten
- Update doku

**Comment by Nic12345678** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wahllokalsystem-65e732175da7e1141c666b0d/issues/it-at-m/Wahllokalsystem/420?planning-poker) with Zenhub @dragonfly28 @GerhardPx @MrSebastian @vjohnslhm
