### ISSUE TITLE
Vereinheitlichung database names wls-monitoring-service

### ISSUE THREAD

**Issue by GerhardPx** [it-at-m/Wahllokalsystem#478]
Die table names sollen sowohl bei den h2-scripts als auch bei den oracle-scripts einheitlich zu CamelCase gemacht werden, properties zu lowercase und SQL-Syntax uppercase. Im Zuge dieses Issues gilt dies für den wls-monitoring-service.

**Comment by Nic12345678** [comment]
Nichts zu tun, da bereits im Laufe der Implementierung beachtet wurde. Issue wird geschlossen. Aus Milestone "Phase 1", Epic "monitoring" und Release "Backend auf spring 3.x.x aktualisiert", entfernt.
