### ISSUE TITLE
Einrichtung der Workflows für das Frontend-Projekt

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#563]
Für die CI/CD Infrastruktur sollen Workflows (Github Actions) erstellt werden.

## 1. Qualitätssicherung
Ein Workflow soll zur Sicherung der Qodequalität dienen.

### Akzeptanzkriterien
- [ ] Linting würd geprüft (z.B. durch ESLint oder Prettier)
- [ ] alle Tests laufen durch, bevor gemerged wird

## 2. Deployment
Ein Workflow soll zur Bereitstellung eines Images für das Deployment dienen. Das Ganze soll analgo zum Backend erfolgen.

### Akzeptanzkriterien
- [ ] Ein Merge auf den `dev`-Branch hat den `latest-dev`-Tag
- [ ] Releases werden mit spezifischer Version gebaut

**Comment by MrSebastian** [comment]
zu 1.:
- ESLint **und** Prettiert sollten aus meiner Sicht zum Einsatz kommen

zu 2.:
- bei dem Akzeptanzkriterium `Releases werden mit spezifischer Version gebaut` würde ich noch ergänzen dass der `latest`-Tag gesetzt werden soll
