### ISSUE TITLE
Exemplarische Backend Kommunikation

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#564]
Zur Verringerung der Einarbeitungszeit soll anhand von Beispieldaten exemplarisch dargestellt werden, wie das Frontend mit dem Backend kommuniziert.

### Akzeptanzkriterien:
- [ ] Zur Verwaltung der API-Anfragen werden Service-Klassen eingerichtet
- [ ] Anfragen können geschickt werden (POST)
- [ ] Antworten können erhalten und gelesen (angezeigt) werden (GET)
- [ ] Die Interaktion mit den gesendeten/gelesenen Daten wird berücksichtigt

**Comment by MrSebastian** [comment]
Das es Service-Klassen sein müssen möchte ich in Frage stellen. Ich bin mir nicht sicher dass die common oder best Practice ist.

Wichtig ist dass es wiederverwenbare API-Calls gibt.

**Comment by vjohnslhm** [comment]
Entscheidung `fetch-utils` vs `axios`:
|  | + | - |
|-------|-------|-------|
| fetch | **bereits im Projekt implementiert**, für einfache anfragen ausreichend | weniger zusatzfunktionen, kompatibilitätsschwierigkeiten mit älteren browsern, manuelle fehlerbehandlung |
| axios | automatische json-konvertierung, verbesserte syntax | extra dependency die installiert werden muss |

Aufgrund der Argumente und der Gewichtung des Arguments, dass die `fetch-utils` bereits im Projekt implementiert sind, wird die `axios`-library nicht eingesetzt werden.
