### ISSUE TITLE
:coffin: `put` + `patch` config entfernen wenn nicht benötigt

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#646]
In den Fetch Utils sind von der Refarch standardmäßig eine `get`-, `post`-, `put`-, und `patch`-config vorhanden. 

Wenn nicht benötigt, sollten die `put`-, und `patch`-config aus dem Code entfernt werden.

**Comment by MrSebastian** [comment]
Beim Wahlvorstand und bei den Wahltermindaten gibt es ein `@PutMapping`
