### ISSUE TITLE
coderabbit configuration

### ISSUE THREAD

**Issue by vjohnslhm** [it-at-m/Wahllokalsystem#650]
Der Coderabbit Bot soll standardmäßig aktiviert werden. In diesem Issue sollen die konkreten Einstellungen gesammelt und abgestimmt werden.

Die Sprache wird weiterhin englisch sein, da opensouce. 

@MrSebastian, @dragonfly28, @GerhardPx, @Nic12345678 bitte durchlesen und abstimmen, welche konfigurationen ihr für notwendig haltet. alternativ können wir es auch gerne gemeinsam im daily durchgehen.

**Comment by vjohnslhm** [comment]
`reviews.profile`:
mögliche Werte: `chill` (normale reviews, wie bisher) oder `assertive` (zusätzliches detaillierteres feedback, das bisher über "nitpick comments" eingesehen werden konnte)
![grafik](https://github.com/user-attachments/assets/16389d25-cfe6-47d9-9d99-c63b307074a1)

bitte abstimmen mit 👍🏽 für `chill` wie bisher, oder 👎🏽 für `assertive`

**Comment by vjohnslhm** [comment]
`reviews.request_changes_workflow`:
`true` pr wird automatisch approved oder `false`, es wird ein manueller approve von einem entwickler benötigt.

bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviwes.high_level_summary`: Zusammenfassung in der PR-Beschreibung
bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.poem`: Gedicht in der Zusammenfassung
![grafik](https://github.com/user-attachments/assets/11f93298-348f-4d0a-8d9e-3c1005ab0a2b)

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.review_status`: Update des aktellen Status des Coderabbit Reviews
zB 
![grafik](https://github.com/user-attachments/assets/822b2252-1556-46aa-8137-8fd25bdad033)
oder 
![grafik](https://github.com/user-attachments/assets/a77e7a50-5420-46ff-bd98-25da2f4e894f)
oder
![grafik](https://github.com/user-attachments/assets/f356cfc6-27f8-4708-b4bb-fc6e3aed0106)

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.auto_title_placeholder`: automatisch generierter pr-titel

bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviews.collapse_walkthrough`: walkthrough als collapsible section (der comment nimmt dann weniger platz im pr ein)
sieht dann so aus:
![grafik](https://github.com/user-attachments/assets/281591f7-c8e3-4385-8392-1e6e40c9bf74)


bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviews.changed_files_summary`: übersicht über die files die geändert wurden
![grafik](https://github.com/user-attachments/assets/12673bcc-1090-4692-b331-acca944cd378)

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.sequence_diagrams`: pr-änderungen als sequenzdiagramm, zB:
![grafik](https://github.com/user-attachments/assets/38b08240-b5ec-4fce-8e98-1b5fc4168762)

bitte abstimmen mit 👍🏽 für `true` oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviews.assess_linked_issues`: überprüfung ob die anforderungen, die im zugehörigen issue beschrieben wurden, beachtet wurden
![grafik](https://github.com/user-attachments/assets/c4981dbd-6617-435b-98d3-35ecfc367f3f)

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.related_issues`: erwähnung von möglicherweise zugehörigen issues in der zusammenfassung

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.related_prs`: erwähnung von möglicherweise zugehörigen pull requests in der zusammenfassung
![grafik](https://github.com/user-attachments/assets/cf713ab2-051d-4f8b-bb2c-a6b563d08d30)

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.suggested_labels`: schlägt mögliche labels für den pr vor

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.suggested_reviewers`: schlägt mögliche reviewer für den pr vor

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.path_filters`: angeben von dateien, die im review ausgeschlossen oder einbezogen werden sollen. zB `[!dist/**, src/**]`

bitte abstimmen mit 👍🏽 für `[ ]` (leer) wie bisher, oder 👎🏽 für `[ <<files>> ]`, die dann noch konkretisiert werden müssen

**Comment by vjohnslhm** [comment]
`reviews.abort_on_close`: coderabbit review wird abgebrochen, wenn der pr währenddessen geschlossen wird

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`reviews.auto_review.enabled`: automatisches review, wenn ein pr erstellt wird

bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviews.auto_review.auto_incremental_review`: automatisches review, jedes mal wenn änderungen zu einem pr gepusht werden

bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviews.auto_review.labels`: automatisches review nur für pull requests mit speziellen labels 

bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviews.auto_review.drafts`: automatisches review, wenn ein pr im draft erstellt wird

bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`reviews.tools`: prüft den code auf zB `markdownlint`, `eslint` etc

bitte abstimmen mit 👍🏽 für `true`, oder 👎🏽 für `false` (wie bisher)

**Comment by vjohnslhm** [comment]
`chat.auto_reply`: automatische antworten vom coderabbit

bitte abstimmen mit 👍🏽 für `true` wie bisher, oder 👎🏽 für `false`

**Comment by vjohnslhm** [comment]
`knowledge_base.type.learnings`: umfang für die wissensdatenbank. `local` verwendet nur die learnings aus dem wls repo, `global` verwendet die learnings aus der it-m-organisation.

bitte abstimmen mit 👍🏽 für `local`, oder 👎🏽 für `global`

**Comment by MrSebastian** [comment]
> `reviews.sequence_diagrams`: pr-änderungen als sequenzdiagramm
> 
> bitte abstimmen mit 👍🏽 für `true` oder 👎🏽 für `false` (wie bisher)

Ich habe eine [Grafik](https://docs.coderabbit.ai/assets/images/coderabbit-sequence-diagram-4fa0b5942c0e789b89537fccfb36dd63.png) gefunden wie das Sequenzdiagramm aussehen könnte

**Comment by MrSebastian** [comment]
Für die Labels könnten wir eine Action verwenden die Labels basierend auf Regeln setzt. Z.b. könnte die Action je nach Service (Ordner) das entsprechende Service-Label setzen.

---

knowledge_base.type.learnings: global könnte zu lustigen Widersprüchen führen

**Comment by MrSebastian** [comment]
@vjohnslhm Danke für die Aufstellung der Konfigurationsoptionen
